version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /packages/cache
    schedule:
      interval: daily
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /packages/dev
    schedule:
      interval: daily
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /packages/envi
    schedule:
      interval: daily
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /packages/exec
    schedule:
      interval: daily
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /packages/log
    schedule:
      interval: daily
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /packages/pip
    schedule:
      interval: daily
    commit-message:
      prefix: chore
