name: build
on:
  workflow_dispatch:
  pull_request:
    branches: ["*", "!*@latest"]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Disable auto CRLF on Windows
        if: matrix.os == 'windows'
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3.3.1
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm run bootstrap

      - name: Build and test
        if: github.event_name != 'pull_request'
        run: npm test

      - name: Build and test since target branch
        if: github.event_name == 'pull_request'
        run: npm test -- "--since=origin/${{ github.base_ref }}"

      - name: Check diff
        run: git diff --exit-code HEAD

  deps-by:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: [dev, envi, exec, log]
    steps:
      - name: Init project
        run: npm init --yes

      - name: Install package
        run: npm install 'https://gitpkg.now.sh/${{ github.repository }}/packages/${{ matrix.pkg }}?${{ github.sha }}'

      - name: Import package
        run: node -e 'const pkg = require("@actions-kit/${{ matrix.pkg }}");'

      - name: Import package in TypeScript
        run: npx --yes ts-node -e 'import * as pkg from "@actions-kit/${{ matrix.pkg }}";'
