name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.3.0

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3.2.5
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Run formatter
        run: npm run format

      - name: Check diff
        run: git diff --exit-code HEAD

  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.3.0

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3.2.5
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Run unit tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.3.0

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3.2.5
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Run static analysis
        run: npm run lint

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.3.0

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3.2.5
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Build this project
        run: npm run clean-build

      - name: Check diff
        run: git diff --exit-code HEAD

  deps-by:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: [io, log]
    steps:
      - name: Init project
        run: npm init --yes

      - name: Install package
        run: npm install 'https://gitpkg.now.sh/${{ github.repository }}/packages/${{ matrix.pkg }}?${{ github.sha }}'

      - name: Import package
        run: node -e 'const pkg = require("@actions-kit/${{ matrix.pkg }}");'

      - name: Import package in TypeScript
        run: npx --yes ts-node -e 'import * as pkg from "@actions-kit/${{ matrix.pkg }}";'
