name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.5.0

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3.3.1
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm run bootstrap

      - name: Build this project
        run: npm run build

      - name: Check diff
        run: git diff --exit-code HEAD

  deps-by:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: [envi, exec, log]
    steps:
      - name: Init project
        run: npm init --yes

      - name: Install package
        run: npm install 'https://gitpkg.now.sh/${{ github.repository }}/packages/${{ matrix.pkg }}?${{ github.sha }}'

      - name: Import package
        run: node -e 'const pkg = require("@actions-kit/${{ matrix.pkg }}");'

      - name: Import package in TypeScript
        run: npx --yes ts-node -e 'import * as pkg from "@actions-kit/${{ matrix.pkg }}";'
